### ISSUE TITLE
4h installing and it keeps going

### ISSUE THREAD

**Issue by dgo2001** [peterdsharpe/AeroSandbox#72] opened 2021-12-13 14:43 UTC
## Bug Description
pip seems to be installing ALL the versions of every dependency needed for aerosandbox I have tried both on win10 latest and on ubuntu 20.04. 

INFO: pip is looking at multiple versions of six to determine which version is compatible with other requirements. This could take a while.
Collecting six>=1.5

It shows that message with every dependency, and it is taking forever to install. pip suggests this:

INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us
 what happened here: https://pip.pypa.io/surveys/backtracking

## Steps to Reproduce
pip install aerosandbox[full]
## System Information

* Operating System: Win 10 and Ubuntu 20.04
* Python Version: 3.7
* AeroSandbox Verion:

**Comment by peterdsharpe** [comment] 2021-12-13 19:17
Hmmm - strange!

Can you confirm that this issue is isolated to `aerosandbox`? And, can you confirm that you are on the latest version of `pip` (do `pip install --upgrade pip` if not)?

For example, do the following commands work?

* `pip install six`
* `pip install aerosandbox` (without `[full]`)

Assuming your `pip` is up-to-date and the problem is indeed limited to `aerosandbox`, please paste the full `pip` stack trace here!

**Comment by peterdsharpe** [comment] 2022-01-02 18:43
Closing, in the absence of any updates.

**Closed by peterdsharpe** 2022-01-02 18:43 UTC
